/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmergencyContact { 'name' : string, 'phone' : PhoneNumber }
export interface FIR {
  'id' : bigint,
  'status' : FIRStatus,
  'title' : string,
  'linkedSOSId' : [] | [bigint],
  'officerNotes' : [] | [string],
  'user' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'location' : Location,
}
export type FIRStatus = { 'filed' : null } |
  { 'closed' : null } |
  { 'under_investigation' : null };
export interface HeatmapPoint {
  'latitude' : number,
  'longitude' : number,
  'severity' : bigint,
  'incidentType' : string,
}
export interface IncidentReport {
  'user' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'location' : Location,
}
export interface Location { 'latitude' : number, 'longitude' : number }
export type NotifType = { 'sos_update' : null } |
  { 'fir_update' : null } |
  { 'new_alert' : null };
export interface Notification {
  'id' : bigint,
  'notifType' : NotifType,
  'userId' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export type PhoneNumber = string;
export interface Profile {
  'contacts' : Array<EmergencyContact>,
  'name' : string,
  'phone' : PhoneNumber,
}
export interface SOSAlert {
  'status' : SOSStatus,
  'user' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'location' : Location,
}
export type SOSStatus = { 'resolved' : null } |
  { 'active' : null } |
  { 'responded' : null };
export interface SafeZone {
  'name' : string,
  'address' : string,
  'location' : Location,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSafeZone' : ActorMethod<[SafeZone], bigint>,
  'askChatbot' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSOSAlert' : ActorMethod<[Location, string], bigint>,
  'fileFIR' : ActorMethod<[string, string, Location, [] | [bigint]], bigint>,
  'getActiveAlertsCount' : ActorMethod<[], bigint>,
  'getAllActiveAlerts' : ActorMethod<[], Array<SOSAlert>>,
  'getAllFIRs' : ActorMethod<[], Array<FIR>>,
  'getAllIncidents' : ActorMethod<[], Array<IncidentReport>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getCallerRole' : ActorMethod<[], UserRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCrimeHeatmapData' : ActorMethod<[], Array<HeatmapPoint>>,
  'getFIR' : ActorMethod<[bigint], [] | [FIR]>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getOwnFIRs' : ActorMethod<[], Array<FIR>>,
  'getOwnIncidents' : ActorMethod<[], Array<IncidentReport>>,
  'getOwnProfile' : ActorMethod<[], Profile>,
  'getOwnSOSAlerts' : ActorMethod<[], Array<SOSAlert>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getResolvedAlertsCount' : ActorMethod<[], bigint>,
  'getSafeZones' : ActorMethod<[], Array<SafeZone>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'submitIncident' : ActorMethod<[Location, string], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateFIRStatus' : ActorMethod<
    [bigint, FIRStatus, [] | [string]],
    undefined
  >,
  'updateSOSStatus' : ActorMethod<[bigint, SOSStatus], undefined>,
  'upsertOwnProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];