/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const SafeZone = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'location' : Location,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SOSStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'active' : IDL.Null,
  'responded' : IDL.Null,
});
export const SOSAlert = IDL.Record({
  'status' : SOSStatus,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : Location,
});
export const FIRStatus = IDL.Variant({
  'filed' : IDL.Null,
  'closed' : IDL.Null,
  'under_investigation' : IDL.Null,
});
export const FIR = IDL.Record({
  'id' : IDL.Nat,
  'status' : FIRStatus,
  'title' : IDL.Text,
  'linkedSOSId' : IDL.Opt(IDL.Nat),
  'officerNotes' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : Location,
});
export const IncidentReport = IDL.Record({
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : Location,
});
export const PhoneNumber = IDL.Text;
export const EmergencyContact = IDL.Record({
  'name' : IDL.Text,
  'phone' : PhoneNumber,
});
export const Profile = IDL.Record({
  'contacts' : IDL.Vec(EmergencyContact),
  'name' : IDL.Text,
  'phone' : PhoneNumber,
});
export const HeatmapPoint = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'severity' : IDL.Nat,
  'incidentType' : IDL.Text,
});
export const NotifType = IDL.Variant({
  'sos_update' : IDL.Null,
  'fir_update' : IDL.Null,
  'new_alert' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : NotifType,
  'userId' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSafeZone' : IDL.Func([SafeZone], [IDL.Nat], []),
  'askChatbot' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSOSAlert' : IDL.Func([Location, IDL.Text], [IDL.Nat], []),
  'fileFIR' : IDL.Func(
      [IDL.Text, IDL.Text, Location, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'getActiveAlertsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllActiveAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
  'getAllFIRs' : IDL.Func([], [IDL.Vec(FIR)], ['query']),
  'getAllIncidents' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallerRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCrimeHeatmapData' : IDL.Func([], [IDL.Vec(HeatmapPoint)], ['query']),
  'getFIR' : IDL.Func([IDL.Nat], [IDL.Opt(FIR)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOwnFIRs' : IDL.Func([], [IDL.Vec(FIR)], ['query']),
  'getOwnIncidents' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
  'getOwnProfile' : IDL.Func([], [Profile], ['query']),
  'getOwnSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getResolvedAlertsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSafeZones' : IDL.Func([], [IDL.Vec(SafeZone)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'submitIncident' : IDL.Func([Location, IDL.Text], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateFIRStatus' : IDL.Func([IDL.Nat, FIRStatus, IDL.Opt(IDL.Text)], [], []),
  'updateSOSStatus' : IDL.Func([IDL.Nat, SOSStatus], [], []),
  'upsertOwnProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const SafeZone = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'location' : Location,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SOSStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'active' : IDL.Null,
    'responded' : IDL.Null,
  });
  const SOSAlert = IDL.Record({
    'status' : SOSStatus,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : Location,
  });
  const FIRStatus = IDL.Variant({
    'filed' : IDL.Null,
    'closed' : IDL.Null,
    'under_investigation' : IDL.Null,
  });
  const FIR = IDL.Record({
    'id' : IDL.Nat,
    'status' : FIRStatus,
    'title' : IDL.Text,
    'linkedSOSId' : IDL.Opt(IDL.Nat),
    'officerNotes' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : Location,
  });
  const IncidentReport = IDL.Record({
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : Location,
  });
  const PhoneNumber = IDL.Text;
  const EmergencyContact = IDL.Record({
    'name' : IDL.Text,
    'phone' : PhoneNumber,
  });
  const Profile = IDL.Record({
    'contacts' : IDL.Vec(EmergencyContact),
    'name' : IDL.Text,
    'phone' : PhoneNumber,
  });
  const HeatmapPoint = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'severity' : IDL.Nat,
    'incidentType' : IDL.Text,
  });
  const NotifType = IDL.Variant({
    'sos_update' : IDL.Null,
    'fir_update' : IDL.Null,
    'new_alert' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : NotifType,
    'userId' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSafeZone' : IDL.Func([SafeZone], [IDL.Nat], []),
    'askChatbot' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSOSAlert' : IDL.Func([Location, IDL.Text], [IDL.Nat], []),
    'fileFIR' : IDL.Func(
        [IDL.Text, IDL.Text, Location, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'getActiveAlertsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllActiveAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
    'getAllFIRs' : IDL.Func([], [IDL.Vec(FIR)], ['query']),
    'getAllIncidents' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallerRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCrimeHeatmapData' : IDL.Func([], [IDL.Vec(HeatmapPoint)], ['query']),
    'getFIR' : IDL.Func([IDL.Nat], [IDL.Opt(FIR)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOwnFIRs' : IDL.Func([], [IDL.Vec(FIR)], ['query']),
    'getOwnIncidents' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
    'getOwnProfile' : IDL.Func([], [Profile], ['query']),
    'getOwnSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getResolvedAlertsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSafeZones' : IDL.Func([], [IDL.Vec(SafeZone)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'submitIncident' : IDL.Func([Location, IDL.Text], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateFIRStatus' : IDL.Func(
        [IDL.Nat, FIRStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSOSStatus' : IDL.Func([IDL.Nat, SOSStatus], [], []),
    'upsertOwnProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };