/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SOSAlert {
    status: SOSStatus;
    user: Principal;
    description: string;
    timestamp: bigint;
    location: Location;
}
export interface FIR {
    id: bigint;
    status: FIRStatus;
    title: string;
    linkedSOSId?: bigint;
    officerNotes?: string;
    user: Principal;
    description: string;
    timestamp: bigint;
    location: Location;
}
export interface EmergencyContact {
    name: string;
    phone: PhoneNumber;
}
export interface Profile {
    contacts: Array<EmergencyContact>;
    name: string;
    phone: PhoneNumber;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type PhoneNumber = string;
export interface IncidentReport {
    user: Principal;
    description: string;
    timestamp: bigint;
    location: Location;
}
export interface HeatmapPoint {
    latitude: number;
    longitude: number;
    severity: bigint;
    incidentType: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface SafeZone {
    name: string;
    address: string;
    location: Location;
}
export interface Notification {
    id: bigint;
    notifType: NotifType;
    userId: Principal;
    isRead: boolean;
    message: string;
    timestamp: bigint;
}
export enum FIRStatus {
    filed = "filed",
    closed = "closed",
    under_investigation = "under_investigation"
}
export enum NotifType {
    sos_update = "sos_update",
    fir_update = "fir_update",
    new_alert = "new_alert"
}
export enum SOSStatus {
    resolved = "resolved",
    active = "active",
    responded = "responded"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSafeZone(safeZone: SafeZone): Promise<bigint>;
    askChatbot(message: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createSOSAlert(location: Location, description: string): Promise<bigint>;
    fileFIR(title: string, description: string, location: Location, linkedSOSId: bigint | null): Promise<bigint>;
    getActiveAlertsCount(): Promise<bigint>;
    getAllActiveAlerts(): Promise<Array<SOSAlert>>;
    getAllFIRs(): Promise<Array<FIR>>;
    getAllIncidents(): Promise<Array<IncidentReport>>;
    getAllProfiles(): Promise<Array<Profile>>;
    getCallerRole(): Promise<UserRole>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCrimeHeatmapData(): Promise<Array<HeatmapPoint>>;
    getFIR(id: bigint): Promise<FIR | null>;
    getMyNotifications(): Promise<Array<Notification>>;
    getOwnFIRs(): Promise<Array<FIR>>;
    getOwnIncidents(): Promise<Array<IncidentReport>>;
    getOwnProfile(): Promise<Profile>;
    getOwnSOSAlerts(): Promise<Array<SOSAlert>>;
    getProfile(user: Principal): Promise<Profile>;
    getResolvedAlertsCount(): Promise<bigint>;
    getSafeZones(): Promise<Array<SafeZone>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationRead(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
    submitIncident(location: Location, description: string): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateFIRStatus(id: bigint, status: FIRStatus, officerNotes: string | null): Promise<void>;
    updateSOSStatus(id: bigint, status: SOSStatus): Promise<void>;
    upsertOwnProfile(profile: Profile): Promise<void>;
}
import type { FIR as _FIR, FIRStatus as _FIRStatus, Location as _Location, NotifType as _NotifType, Notification as _Notification, Profile as _Profile, SOSAlert as _SOSAlert, SOSStatus as _SOSStatus, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSafeZone(arg0: SafeZone): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSafeZone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSafeZone(arg0);
            return result;
        }
    }
    async askChatbot(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askChatbot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askChatbot(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSOSAlert(arg0: Location, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSOSAlert(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSOSAlert(arg0, arg1);
            return result;
        }
    }
    async fileFIR(arg0: string, arg1: string, arg2: Location, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.fileFIR(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fileFIR(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getActiveAlertsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAlertsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAlertsCount();
            return result;
        }
    }
    async getAllActiveAlerts(): Promise<Array<SOSAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveAlerts();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveAlerts();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFIRs(): Promise<Array<FIR>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFIRs();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFIRs();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIncidents(): Promise<Array<IncidentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncidents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncidents();
            return result;
        }
    }
    async getAllProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return result;
        }
    }
    async getCallerRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrimeHeatmapData(): Promise<Array<HeatmapPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrimeHeatmapData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrimeHeatmapData();
            return result;
        }
    }
    async getFIR(arg0: bigint): Promise<FIR | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFIR(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFIR(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnFIRs(): Promise<Array<FIR>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnFIRs();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnFIRs();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnIncidents(): Promise<Array<IncidentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnIncidents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnIncidents();
            return result;
        }
    }
    async getOwnProfile(): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnProfile();
            return result;
        }
    }
    async getOwnSOSAlerts(): Promise<Array<SOSAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnSOSAlerts();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnSOSAlerts();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return result;
        }
    }
    async getResolvedAlertsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getResolvedAlertsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResolvedAlertsCount();
            return result;
        }
    }
    async getSafeZones(): Promise<Array<SafeZone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafeZones();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafeZones();
            return result;
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitIncident(arg0: Location, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitIncident(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitIncident(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateFIRStatus(arg0: bigint, arg1: FIRStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFIRStatus(arg0, to_candid_FIRStatus_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFIRStatus(arg0, to_candid_FIRStatus_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSOSStatus(arg0: bigint, arg1: SOSStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSOSStatus(arg0, to_candid_SOSStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSOSStatus(arg0, to_candid_SOSStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upsertOwnProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertOwnProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertOwnProfile(arg0);
            return result;
        }
    }
}
function from_candid_FIRStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FIRStatus): FIRStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FIR_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FIR): FIR {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_NotifType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotifType): NotifType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SOSAlert_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SOSAlert): SOSAlert {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SOSStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SOSStatus): SOSStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FIR]): FIR | null {
    return value.length === 0 ? null : from_candid_FIR_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _FIRStatus;
    title: string;
    linkedSOSId: [] | [bigint];
    officerNotes: [] | [string];
    user: Principal;
    description: string;
    timestamp: bigint;
    location: _Location;
}): {
    id: bigint;
    status: FIRStatus;
    title: string;
    linkedSOSId?: bigint;
    officerNotes?: string;
    user: Principal;
    description: string;
    timestamp: bigint;
    location: Location;
} {
    return {
        id: value.id,
        status: from_candid_FIRStatus_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        linkedSOSId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.linkedSOSId)),
        officerNotes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.officerNotes)),
        user: value.user,
        description: value.description,
        timestamp: value.timestamp,
        location: value.location
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notifType: _NotifType;
    userId: Principal;
    isRead: boolean;
    message: string;
    timestamp: bigint;
}): {
    id: bigint;
    notifType: NotifType;
    userId: Principal;
    isRead: boolean;
    message: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        notifType: from_candid_NotifType_n23(_uploadFile, _downloadFile, value.notifType),
        userId: value.userId,
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SOSStatus;
    user: Principal;
    description: string;
    timestamp: bigint;
    location: _Location;
}): {
    status: SOSStatus;
    user: Principal;
    description: string;
    timestamp: bigint;
    location: Location;
} {
    return {
        status: from_candid_SOSStatus_n7(_uploadFile, _downloadFile, value.status),
        user: value.user,
        description: value.description,
        timestamp: value.timestamp,
        location: value.location
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filed: null;
} | {
    closed: null;
} | {
    under_investigation: null;
}): FIRStatus {
    return "filed" in value ? FIRStatus.filed : "closed" in value ? FIRStatus.closed : "under_investigation" in value ? FIRStatus.under_investigation : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sos_update: null;
} | {
    fir_update: null;
} | {
    new_alert: null;
}): NotifType {
    return "sos_update" in value ? NotifType.sos_update : "fir_update" in value ? NotifType.fir_update : "new_alert" in value ? NotifType.new_alert : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    active: null;
} | {
    responded: null;
}): SOSStatus {
    return "resolved" in value ? SOSStatus.resolved : "active" in value ? SOSStatus.active : "responded" in value ? SOSStatus.responded : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SOSAlert>): Array<SOSAlert> {
    return value.map((x)=>from_candid_SOSAlert_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FIR>): Array<FIR> {
    return value.map((x)=>from_candid_FIR_n10(_uploadFile, _downloadFile, x));
}
function to_candid_FIRStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FIRStatus): _FIRStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_SOSStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SOSStatus): _SOSStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FIRStatus): {
    filed: null;
} | {
    closed: null;
} | {
    under_investigation: null;
} {
    return value == FIRStatus.filed ? {
        filed: null
    } : value == FIRStatus.closed ? {
        closed: null
    } : value == FIRStatus.under_investigation ? {
        under_investigation: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SOSStatus): {
    resolved: null;
} | {
    active: null;
} | {
    responded: null;
} {
    return value == SOSStatus.resolved ? {
        resolved: null
    } : value == SOSStatus.active ? {
        active: null
    } : value == SOSStatus.responded ? {
        responded: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
